# git_test


0523-1615

git push
To https://github.com/zoofighter/git_test.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/zoofighter/git_test.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.